# Generated by Django 5.2.7 on 2025-10-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('title', models.CharField(max_length=10)),
                ('on_stock', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('ratings', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
